from typing import List, Optional

from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    """
    Request body for the RAG question-answering endpoints
    (POST /api/v1/ask and POST /api/v1/stream).

    WHY top_k instead of size?
    In the hybrid search endpoint we return many hits for the user to browse.
    In the RAG endpoint the hits are never shown directly — they're fed to the
    LLM as context. More chunks = longer prompt = slower generation + higher
    risk of the LLM losing focus. 3 chunks is enough context for a focused
    answer; 10 is the practical ceiling for a 1B-parameter model like llama3.2:1b.

    WHY expose `model` in the request?
    Different questions benefit from different models. A simple factual question
    works fine with llama3.2:1b (fast, low memory). A nuanced comparison across
    papers benefits from a larger model if available. Exposing the field lets
    the UI or caller choose per-request without restarting the API.
    """

    query: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="The question to answer using retrieved paper chunks",
    )
    top_k: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Number of chunks to retrieve and pass to the LLM as context",
    )
    use_hybrid: bool = Field(
        default=True,
        description="Use hybrid search (BM25 + vector). False = BM25 only.",
    )
    model: str = Field(
        default="llama3.2:1b",
        description="Ollama model to use for answer generation",
    )
    categories: Optional[List[str]] = Field(
        default=None,
        description="Filter retrieved chunks to these arXiv categories (e.g. ['cs.AI'])",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "query": "What are transformers in machine learning?",
                "top_k": 3,
                "use_hybrid": True,
                "model": "llama3.2:1b",
                "categories": ["cs.AI", "cs.LG"],
            }
        }
    }


class AskResponse(BaseModel):
    """
    Response from the non-streaming RAG endpoint (POST /api/v1/ask).

    WHY not return the raw chunks?
    The chunks are the retrieval step's internal detail. The user asked a
    question and wants an answer, not 3 × 600-word passages to read themselves.
    `chunks_used` tells them how much context the LLM had; `sources` lets them
    follow up by reading the original papers.

    sources:     PDF URLs generated from the arxiv_ids of retrieved chunks.
                 Format: "https://arxiv.org/pdf/{arxiv_id}.pdf"
                 Generated by OllamaClient, not by the LLM (LLMs hallucinate URLs).
    search_mode: "hybrid" or "bm25" — tells the caller whether semantic search
                 was used. Useful for debugging when answers seem off-topic.
    """

    query: str = Field(..., description="The original question")
    answer: str = Field(..., description="LLM-generated answer based on retrieved chunks")
    sources: List[str] = Field(..., description="PDF URLs of papers used as context")
    chunks_used: int = Field(..., description="Number of chunks passed to the LLM")
    search_mode: str = Field(..., description="Search mode used: 'hybrid' or 'bm25'")

    model_config = {
        "json_schema_extra": {
            "example": {
                "query": "What are transformers in machine learning?",
                "answer": "Transformers are a neural network architecture based on self-attention...",
                "sources": [
                    "https://arxiv.org/pdf/1706.03762.pdf",
                    "https://arxiv.org/pdf/1810.04805.pdf",
                ],
                "chunks_used": 3,
                "search_mode": "hybrid",
            }
        }
    }
